#ifndef RESPONSES_HPP
# define RESPONSES_HPP

//reply and error numeric codes
# define RPL_UMODEISNBR " 221 "
# define RPL_AWAYNBR  " 301 "
# define RPL_ENDOFWHONBR " 315 "
# define RPL_CHANNELMODEISNBR " 324 "
# define RPL_NOTOPICNBR " 331 "
# define RPL_TOPICNBR " 332 "
# define RPL_INVITINGNBR " 341 "
# define RPL_WHOREPLYNBR " 352 "
# define RPL_BANLISTNBR " 367 "
# define RPL_ENDOFBANLISTNBR " 368 "
# define ERR_NOSUCHNICKNBR " 401 "
# define ERR_NOSUCHSERVERNBR " 402 "
# define ERR_NOSUCHCHANNELNBR " 403 "
# define ERR_CANNOTSENDTOCHANNBR " 404 "
# define ERR_TOOMANYCHANNELSNBR " 405 "
# define ERR_TOOMANYTARGETSNBR " 407 "
# define ERR_NORECIPIENTNBR " 411 "
# define ERR_NOTEXTTOSENDNBR " 412 "
# define ERR_NOTOPLEVELNBR " 413 "
# define ERR_WILDTOPLEVELNBR " 414 "
# define ERR_NONICKNAMEGIVENNBR " 431 "
# define ERR_ERRONEUSNICKNAMENBR " 432 "
# define ERR_NICKNAMEINUSENBR " 433 "
# define ERR_NICKCOLLISIONNBR " 436 "
# define ERR_NOTONCHANNELNBR " 442 "
# define ERR_USERONCHANNELNBR " 443 "
# define ERR_NEEDMOREPARAMSNBR " 461 "
# define ERR_ALREADYREGISTEREDNBR " 462 "
# define ERR_PASSWDMISMATCHNBR " 464 "
# define ERR_KEYSETNBR " 467 "
# define ERR_CHANNELISFULLNBR " 471 "
# define ERR_UNKNOWNMODENBR " 472 "
# define ERR_INVITEONLYCHANNBR " 473 "
# define ERR_BANNEDFROMCHANNBR " 474 "
# define ERR_BADCHANMASKNBR " 476 "
# define ERR_CHANOPRIVSNEEDEDNBR " 482 "
# define ERR_UMODEUNKNOWNFLAGNBR " 501 "
# define ERR_USERSDONTMATCHNBR " 502 "

//reply messages
# define RPL_UMODEIS "<user mode string>"
# define RPL_AWAY "<nick> :<away message>"
# define RPL_ENDOFWHO "<name> :End of /WHO list"
# define RPL_CHANNELMODEIS "<channel> <mode> <mode params>"
# define RPL_NOTOPIC "<channel> :No topic is set"
# define RPL_TOPIC "<channel> :<topic>"
# define RPL_INVITING "<channel> <nick>"
# define RPL_WHOREPLY "<channel> <user> <host> <server> <nick> <H|G>[*][@|+] :<hopcount> <real name>"
# define RPL_BANLIST "<channel> <banid>"
# define RPL_ENDOFBANLIST "<channel> :End of channel ban list"

//error messages
# define ERR_ACCEPT "Error on accept"
# define ERR_ALREADYREGISTRED " :You may not reregister"
# define ERR_BADCHANMASK " :Invalid channel name"
# define ERR_BANNEDFROMCHAN "<channel> :Cannot join channel (+b)"
# define ERR_BIND "Error on bind"
# define ERR_CANNOTSENDTOCHAN "<channel name> :Cannot send to channel"
# define ERR_CHANNELISFULL "<channel> :Cannot join channel (+l)"
# define ERR_CHANOPRIVSNEEDED "<channel> :You're not channel operator"
# define ERR_ERRONEUSNICKNAME "<nick> :Erroneus nickname"
# define ERR_FCNTL "Error on fcntl"
# define ERR_INVITEONLYCHAN "<channel> :Cannot join channel (+i)"
# define ERR_KEYSET "<channel> :Channel key already set"
# define ERR_LISTEN "Error on listen"
# define ERR_NEEDMOREPARAMS "<command> :Not enough parameters"
# define ERR_NICKCOLLISION "<nick> :Nickname collision KILL"
# define ERR_NICKNAMEINUSE "<nick> :Nickname is already in use"
# define ERR_NONICKNAMEGIVEN ":No nickname given"
# define ERR_NORECIPIENT ":No recipient given (<command>)"
# define ERR_NOSUCHCHANNEL "<channel name> :No such channel"
# define ERR_NOSUCHNICK "<nickname> :No such nick/channel"
# define ERR_NOSUCHSERVER "<server name> :No such server"
# define ERR_NOTEXTTOSEND ":No text to send"
# define ERR_NOTONCHANNEL "<channel> :You're not on that channel"
# define ERR_NOTOPLEVEL "<mask> :No toplevel domain specified"
# define ERR_PASSWDMISMATCH ":Password incorrect"
# define ERR_POLL "Error on poll"
# define ERR_RECV "Error on recv"
# define ERR_SETSOCKOPT "Error on setsockopt"
# define ERR_SOCKET "Error creating socket"
# define ERR_TOOMANYCHANNELS "<channel name> :You have joined too many \                         channels"
# define ERR_TOOMANYTARGETS "<target> :Duplicate recipients. No message delivered"
# define ERR_UMODEUNKNOWNFLAG ":Unknown MODE flag"
# define ERR_UNKNOWNMODE "<char> :is unknown mode char to me"
# define ERR_USER "Error on User"
# define ERR_USERONCHANNEL "<user> <channel> :is already on channel"
# define ERR_USERSDONTMATCH ":Cant change mode for other users"
# define ERR_WILDTOPLEVEL "<mask> :Wildcard in toplevel domain"



#endif